# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Livel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Livel
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '~> 1.0.1.18'

  target 'LivelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LivelUITests' do
    # Pods for testing
  end

end
